//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Auctions.Export
{
    public partial class Model
    {
        public Model()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
        public short MakeId { get; set; }
    
        public virtual Make Make { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
