//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Auctions.Export
{
    public partial class Sale
    {
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<DateTime> Date { get; set; }
        public short ModelId { get; set; }
        public virtual Model Model { get; set; }
    }
}
